import numpy as np
import time
import os
import soundfile as sf
import sounddevice as sd

from src.utility.pyaudio_runner import play_and_record
from src.utility.play_audio import play_audio
from src.utility.record_audio import record_audio

# --- HARDWARE CALIBRATION CONSTANTS ---
LOOPBACK_DELAY_MS = 42.812  # Your calibrated hardware offset
SAMPLE_RATE = 48000
NUM_ITERATIONS = 3     # 50 for final test
SILENCE_GAP_SEC = 3.0  # Time allowed for Polly to speak her wake reply

class HostTestHarness:
    def __init__(self):
        print(f"[*] Host Test Harness Initialized")
        print(f"    - Running {NUM_ITERATIONS} automated loops")
        print(f"    - Compensating Hardware Delay: {LOOPBACK_DELAY_MS} ms\n")

    def load_stimulus_files(self):
        """Loads and verifies the crispy wav files generated by macOS say."""
        if not os.path.exists("wake_phrase.wav") or not os.path.exists("command_phrase.wav"):
            raise FileNotFoundError("Missing 'wake_phrase.wav' or 'command_phrase.wav'. Run macOS 'say' first!")
        
        # soundfile automatically detects layout via header and forces float32
        wake_audio, _ = sf.read("wake_phrase.wav", dtype='float32')
        command_audio, _ = sf.read("command_phrase.wav", dtype='float32')
        
        # Ensure they are flat 1D mono arrays
        if len(wake_audio.shape) > 1: wake_audio = wake_audio[:, 0]
        if len(command_audio.shape) > 1: command_audio = command_audio[:, 0]
        
        return wake_audio, command_audio

    def execute_suite(self):
        wake_audio, command_audio = self.load_stimulus_files()
        
        # Build a continuous timeline array: [ Wake ] -> [ 3s Silence ] -> [ Command ]
        silence_buffer = np.zeros(int(SAMPLE_RATE * SILENCE_GAP_SEC), dtype=np.float32)
        full_stimulus = np.concatenate([wake_audio, silence_buffer, command_audio])
        
        # Calculate strict timing boundaries relative to t=0 (in seconds)
        wake_end_time = len(wake_audio) / SAMPLE_RATE
        command_start_time = wake_end_time + SILENCE_GAP_SEC
        command_end_time = command_start_time + (len(command_audio) / SAMPLE_RATE)
        
        hardware_offset_sec = LOOPBACK_DELAY_MS / 1000.0

        wake_latencies = []
        reply_latencies = []

        print("="*65)
        print("  LAUNCHING 50-RUN AUTOMATED LATENCY SUITE")
        print("  Ensure SUT computer is connected and GUI/CLI is running.")
        print("="*65)
        input("Press Enter to begin automated testing...")

        for i in range(1, NUM_ITERATIONS + 1):
            print(f"Running iteration {i}/{NUM_ITERATIONS}...", end='\r')
            
            # Full-duplex audio operation using sounddevice
            # Automatically records line-in while playing the full_stimulus out
            recorded = sd.playrec(full_stimulus, samplerate=SAMPLE_RATE, channels=1, dtype='float32')
            sd.wait()  # Wait until the full play/record timeline completes
            
            # Flatten recording array
            recorded = recorded.flatten()
            
            # Compute rolling RMS energy envelope (10ms windows, 50% overlap)
            hop_size = int(SAMPLE_RATE * 0.01)
            win_size = int(SAMPLE_RATE * 0.02)
            num_frames = (len(recorded) - win_size) // hop_size
            
            energy = np.array([np.sqrt(np.mean(recorded[j*hop_size : j*hop_size + win_size]**2)) for j in range(num_frames)])
            timeline = np.array([(j * hop_size + (win_size / 2)) / SAMPLE_RATE for j in range(num_frames)])
            
            # Establish dynamic noise gate (12% of peak energy captured during this specific run)
            noise_threshold = np.max(energy) * 0.12
            
            w_lat, r_lat = None, None
            
            # Landmark 1: Parse Wake-Up Latency (Look between Wake Word End and Command Start)
            for idx, e in enumerate(energy):
                t_event = timeline[idx]
                if (wake_end_time + hardware_offset_sec) < t_event < command_start_time:
                    if e > noise_threshold:
                        # Latency = Event Time - Expected Event Time - Hardware Constant
                        w_lat = (t_event - wake_end_time - hardware_offset_sec) * 1000
                        break
                        
            # Landmark 2: Parse Processing Loop Latency (Look anytime after Command Word End)
            for idx, e in enumerate(energy):
                t_event = timeline[idx]
                if t_event > (command_end_time + hardware_offset_sec):
                    if e > noise_threshold:
                        r_lat = (t_event - command_end_time - hardware_offset_sec) * 1000
                        break
            
            if w_lat: wake_latencies.append(w_lat)
            if r_lat: reply_latencies.append(r_lat)
            
            # Cooldown window to let SUT completely clear its pipelines
            time.sleep(1.5)

        # Process and output the statistical analytical report
        self.generate_report(wake_latencies, reply_latencies)

    def generate_report(self, wake_list, reply_list):
        print("\n\n" + "="*65)
        print("         HOST AUTOMATED LATENCY METRICS REPORT (N=50)")
        print("="*65)
        
        for name, dataset in [("SUT Wake-Up Latency", wake_list), ("SUT Total Reply Latency", reply_list)]:
            if len(dataset) == 0:
                print(f"{name}: 0 successful samples captured. Check your cable volumes!")
                continue
                
            arr = np.array(dataset)
            success_p = (len(dataset) / NUM_ITERATIONS) * 100
            
            print(f"Metrics for {name}:")
            print(f"  -> Capture Success Rate: {success_p:.1f}% ({len(dataset)}/{NUM_ITERATIONS})")
            print(f"  -> Mean Latency (μ):     {np.mean(arr):.2f} ms")
            print(f"  -> Jitter (Std Dev σ):   {np.std(arr):.2f} ms")
            print(f"  -> Best-Case Run (Min):  {np.min(arr):.2f} ms")
            print(f"  -> Worst-Case Run (Max): {np.max(arr):.2f} ms")
            print(f"  -> P95 Worst Case:       {np.percentile(arr, 95):.2f} ms")
            print(f"  -> P99 Worst Case:       {np.percentile(arr, 99):.2f} ms")
            print("-" * 65)


if __name__ == "__main__":
    harness = HostTestHarness()
    try:
        harness.execute_suite()
    except Exception as e:
        print(f"❌ Harness Error: {e}")